smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "apoorvakamerkar7@gmail.com"
  password: "vxxyjbksusyaucse"
  
db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "Apoorva@0701"
  database: "g13ecommerce"